### ISSUE TITLE
At test cases for indexing mixed schema versions

### ISSUE THREAD

**Issue by Bento007** [HumanCellAtlas/data-store#1046]

**Comment by hannes-ucsc** [comment]
This is a follow-up to an emergency fix (#1035) that was part of the integration effort during the March DCP meeting.

The schema mix was caused by a new file introduced by the [v5 example bundle](https://github.com/HumanCellAtlas/metadata-schema/tree/master/examples/bundles/v5/Q4DemoSS2). The new file is called 'files.json` (yes, a file named `files.json`) and its major schema version is 1. All other files in that bundle reference schemata at major version 5.
