### ISSUE TITLE
Duplicate bundles associated with DSS 504 errors

### ISSUE THREAD

**Issue by xbrianh** [HumanCellAtlas/data-store#1098]
During bundle/PUT submission to DSS, ingest encountered a 504 error and retried. Both operations successfully uploaded a bundle to the DSS, resulting in two versions.

This appears to have occurred twice on 28-March, 2018. The effected bundles are:
`17a3d288-01a0-464a-9599-7375fda3353d.2018-03-28T150956.976400Z`
`17a3d288-01a0-464a-9599-7375fda3353d.2018-03-28T151023.074974Z`
`59a9ba09-998d-4dde-98db-c6a05b5481ee.2018-03-28T182154.619685Z`
`59a9ba09-998d-4dde-98db-c6a05b5481ee.2018-03-28T182220.776570Z`

A possible cause may be that the dss-prod lambda not responding within the API Gateway timeout. Lambda timeout is 5 minutes, while API Gateway timeout is 29 seconds. Note that the bundle versions are almost exactly 26 seconds apart.

Indeed, we can find dss-prod lambda durations longer than 29 seconds:
>  RequestId: 7f833f8b-32b4-11e8-abb0-477def236f75\tDuration: 36038.25 ms\tBilled Duration: 36100 ms \tMemory Size: 128 MB\tMax Memory Used: 73 MB
>  RequestId: 800f04cb-32b4-11e8-b671-8173331ce5c6\tDuration: 36969.55 ms\tBilled Duration: 37000 ms \tMemory Size: 128 MB\tMax Memory Used: 73 MB
>  RequestId: 7f443b02-32b4-11e8-9c60-e3f5b738ea44\tDuration: 38453.51 ms\tBilled Duration: 38500 ms \tMemory Size: 128 MB\tMax Memory Used: 73 MB
>  RequestId: 7fcb930f-32b4-11e8-8e3f-71c37960d666\tDuration: 39173.49 ms\tBilled Duration: 39200 ms \tMemory Size: 128 MB\tMax Memory Used: 73 MB
>  RequestId: 7f5837de-32b4-11e8-a1fe-918d8506d64d\tDuration: 40014.84 ms\tBilled Duration: 40100 ms \tMemory Size: 128 MB\tMax Memory Used: 73 MB
>  RequestId: 7f54dc13-32b4-11e8-9e30-ede523155a18\tDuration: 40409.30 ms\tBilled Duration: 40500 ms \tMemory Size: 128 MB\tMax Memory Used: 73 MB
>  RequestId: 7f4f858a-32b4-11e8-ac8b-9bc3fe1e4727\tDuration: 41104.80 ms\tBilled Duration: 41200 ms \tMemory Size: 128 MB\tMax Memory Used: 73 MB
>  RequestId: 7f61fbab-32b4-11e8-bc51-498e7a3c0350\tDuration: 41794.91 ms\tBilled Duration: 41800 ms \tMemory Size: 128 MB\tMax Memory Used: 73 MB
>  RequestId: 7f4c029c-32b4-11e8-9745-9b49d2918b38\tDuration: 42003.76 ms\tBilled Duration: 42100 ms \tMemory Size: 128 MB\tMax Memory Used: 73 MB

Unfortunately API Gateway logging was not enabled on prod (it has since been enabled).

API Gateway timeout docs:
https://docs.aws.amazon.com/apigateway/latest/developerguide/limits.html

A possible fix may be to require version in bundle/PUT, which will return `requests.codes.conflict` when submitting an existing bundle.

**Comment by hannes-ucsc** [comment]
> A possible fix may be to require version in bundle/PUT, which will return requests.codes.conflict when submitting an existing bundle.

Yes, that and making `PUT /bundle` idempotent. For example, SQS' `CreateQueue` is idempotent, which is immensely useful. It only raises a 409 if the creation parameters are different.

**Comment by hannes-ucsc** [comment]
@xbrianh points out that PUT /bundle is already almost idempotent, if it weren't for the fact that version is optional.

**Comment by xbrianh** [comment]
Causes:
* S3 latency may occasionally be large

Fixes:
* Version generated in CLI by default
* speed up PUT /bundle (reconfigure retry , etc)
* Shorter socket timeouts

**Comment by tburdett** [comment]
Here's my view: if ingest receives an server error response when writing to the producer API (or indeed anyone using the consumer API), I would expect the DSS to take action to resolve that error. It seems kind of unreasonable to return a 504 and then expect the client to interrogate the DSS to figure out how much of their request was successful... and can you even guarantee the error is something that is recoverable by a client?

On `PUT /bundle` requests requiring a version: I'm not against this solution but why not use ETag so I can do a conditional PUT instead of parameter? If it's a parameter, this pushes a lot of DSS lifecycle logic being into clients (clients of the producer API must do a lookup by UUID, retrieve current version, increment by 1 etc.): effectively this transforms a server error into a client error on retry, and this time the client error gives no indication of the consistency of the bundle that resulted from the first request. Worse, clients and servers are now more tightly coupled as the client must have baked in logic that contains the series of calls to unpick the failed first request, and if e.g. a DELETE endpoint changes this code breaks.

So my minimum expectation here is:

- if DSS returns a server error, the DSS rolls back anything that happened during that request
- if version is required, a PUT request that exactly repeats an earlier PUT request would never cause a conflict
- if version is not required, a version-less request should be assumed to be v1; at this point a conflict is reasonable (but not if previous attempts have resulted in an error)

My suggested fixes:

1. cleanup after a fail
2. validate the PUT request, return a 202 if valid and have the DSS retry until successful. If you choose this option, the producer API will need an endpoint that clients can poll for success.  We could actually use this anyway to determine when a bundle creation event (including file transfer from staging) is successfully completed

**Comment by ttung** [comment]
The version is a timestamp and is trivial to generate client-side.  It would not require asking the server for the version.

I don't think (1) is practical to do because there will **always** be race conditions.  (2) is fine, but adds a lot of complexity compared to just (a) making version required and (b) hiding that logic inside the client such that end users are never exposed to that detail.

**Comment by tburdett** [comment]
Making version required won't solve the problem, it will just transform a server error into a client error.

Now, the client will send a request, receive a 504, retry the exact same request and receive a 409 (unless the first request was actually successful, in which case the original 504 error code is wrong).  How is a client supposed to interpret this? It has no idea how much of the bundle storage was successful. It is much less practical for clients (one right now, potentially many more in future?) to do (1) - cleanup after a fail - than the server.

IMHO, asking all clients to bake in "repair" logic to work around an implementation detail (choice of AWS lambda, at a guess?) isn't a reasonable expectation.

**Comment by kislyuk** [comment]
@tburdett, while we will strive to reduce the frequency of errors, we will encounter them anyway no matter what. (In this case the error doesn't seem to have anything to do with Lambda; it's most likely related to the long tail of S3 latency, for which the solution is aggressive timeouts on the server. We will fix this issue, but we will never fix all sources of server side errors.)

Sporadic errors will always happen, and the solution to building a robust system in the face of sporadic errors is retryability and idempotency. That is a general API design best practice. The client's responsibility is to retry any 500 series errors at least 5 times with exponential back-off over a minute, or as instructed by the `Retry-After` header. The server's responsibility is to produce accurate status codes, and to make sure that operations can be made idempotent. In the case of DSS PUT bundle, that is already the case: if I call PUT bundle with the exact same payload as my original request, I'll get an OK response in return (but if I change the contents of the bundle without changing UUID+version, I will get an error back).

The version was designed specifically to **not** require write-after-read incrementing (which would open up a race condition), and to minimize the chance of collisions by utilizing a high precision timestamp as a version. This means the client should just generate the version together with UUID and use those together where you would use a UUID.

Finally, if you're implementing the client side in Python, I would suggest using the DCP CLI (which includes Python bindings for the DSS) as going forward, these bindings will provide the best practice implementation of the retry logic I described, etc.

**Comment by tburdett** [comment]
@kislyuk this isn't the behaviour we're observing though - we're doing a `PUT`, getting a 500 response, then doing a second identical `PUT` which gives an OK; however, duplicate bundles are being stored.

Given the optional timestamp, I guess it is fair to say that these bundles aren't true duplicates (although our PUT requests are identical with a 5 second backoff time).  However, if the client generates the timestamp to ensure they are "true" duplicates, according to @xbrianh's response:

> A possible fix may be to require version in bundle/PUT, which will return `requests.codes.conflict` when submitting an existing bundle

...indicating repeat requests after a 504 will result in a 409 conflict on repeat requests, so my question still is: how is the client meant to determine how to handle this?

**Comment by kislyuk** [comment]
@tburdett The behavior you're observing is the consequence of letting the server specify the timestamp.

If you specify both the UUID and the timestamp, and create a bundle, then call the same method again with the same payload, you will **not** receive a 409, you will receive a 200 series code. If you change the payload however, you will receive a 409 Conflict.

That is what I meant when I said the system is designed for idempotency.

**Comment by tburdett** [comment]
We can certainly use the DCP CLI, but won't we just see the same behaviour?

Also, this solution comes with a different set of objections from me relating to tight coupling... I don't particularly want to open that thread up here :smile:

**Comment by hannes-ucsc** [comment]
So user requests `PUT /bundles` without a version. Gets a 504. A bundle is created on storage anyways. User retries, with or without version. Another bundle version is created unless the user magically guesses the version that was auto-generated the first time. If we keep version optional and assuming we educate users on the consequences of omitting the version, which educated user is going to chose the risky alternative in favor of a mild convenience? I for sure wouldn't.

We should reduce the probability of those 504s *and* make recovering from them straight-forward. Asking users to play Russian roulette isn't part of that plan in my opinion.

**Comment by hannes-ucsc** [comment]
But here is the thing: We would tempt users into thinking that they can omit the version which they really can't if they want their software to be correct. Only when things fail for them do we explain that the version is de-facto required. That's a classic bait and switch and it would annoy me royally if I were a user.

I am fully onboard with flattening the learning curve by having sensible defaults. `version=None` is not a sensible default because it jeopardizes correctness.

**Comment by hannes-ucsc** [comment]
Also, following REST recommendations,  after a successful `PUT <url>` one should be able to do `GET <url>`. With version being optional, this is not generally the case. REST also says that PUTs should always be idempotent which, again, is contradicted if version is optional.

**Comment by xbrianh** [comment]
My current understanding:

Our ambition is to provide a friendly DSS, which means API calls that don't require a bunch of abstruse parameters such as idiosyncratically formatted version strings. (Note that the word abstruse is itself abstruse.)

Our downfall is that our friendly interface occasionally produces unfriendly results, in this case duplicated bundles.

To address this, we might take two paths:
1. Developer-easy (user-hard) require version during PUT /bundle
2. Developer-hard (user-easy) speed up PUT /bundle so this is less likely to occur, and promote providing version during PUT /bundle as best practice.

In pursuit of 2, I understand that `ingest` already generates client-side versions in their development branch. We might also look into having the `dcp-cli` auto-generate version strings, and promoting the use of the `dcp-cli` overall in lieu of REST API calls.

Note that if we go down path 2 and fail to significantly mitigate this issue, the usability of the DSS will be diminished anyway due to frequent errors.

**Comment by briandoconnor** [comment]
@xbrianh what does the response look like when you create a new bundle but the underlying S3 operations take a long time.  Do you see a timeout?  Or are you designing the API like other parts of the API where bundle creation is asynchronous... you immediately get the assigned timestamp and can check later on the bundle creation status?

**Comment by xbrianh** [comment]
@briandoconnor The request is synchronous. If S3, or something else, takes a long time, we risk API Gateway timeouts (504 errors).

**Comment by kislyuk** [comment]
As mentioned earlier, S3 has a latency long tail, the solution to which is to set timeouts aggressively so stalled out requests are retried quickly.

**Comment by tburdett** [comment]
My 2 cents: if timeouts are likely, make the request asynchronous and make the client responsible for checking completion.  If timeouts are not likely, synchronous is fine.  In case of error, ingest will retry, multiple versions will get created, but if this a small risk I'm happy for the DSS to worry about the cost of occasional spurious version churn.
