### ISSUE TITLE
Allow a file to be included in more than one bundle

### ISSUE THREAD

**Issue by aaclan-ebi** [HumanCellAtlas/data-store#1172]
Hi bluebox

During an export of a result/analysis bundle to DSS, we specify files from the input bundle to be included in the analysis bundle if it has an exact same content like the data files and project.json metadata file. Moreover, it won't be possible to reupload the data files from previous submission since the upload area where those were previously uploaded will be already deleted by the time the result bundle export happens. 

We specify the same uuid and version of the file when we create a the bundle in DSS. 

It seems that this conflicts the bluebox specification that a file cannot be in more than one bundle. 
Would it be possible to allow this behaviour so that we'll be able to reuse same files in the result bundles. This would also avoid having files duplicated in the data store.

Many thanks!

**Comment by hannes-ucsc** [comment]
Thank you for bringing this to our attention, @aaclan-ebi.

First of all, I think this is an opportune moment to rethink the inclusion of an input bundle's metadata  in the analysis bundle, aka "copy forward". If we stop doing that, something I've been pushing for, this issue becomes moot.

Second, if we continue copy-forward, the copy-forwarded metadata should be cordoned off in a  folder in the analysis bundle. If the file is called `foo.js` in the input bundle it should be called `input/joo.js` in the output bundle. I think this is advisable in order to avoid conflicts.  

Correct me if I am wrong but the file name is the only essential property of a file object in DSS (if you are familiar with Unix filesystem, DSS blobs are analogous to inodes, while DSS files are dirents). Changing the name of an input file in the analysis bundle inevitably means that the input and analysis bundles can't share a file object, again rendering this issue moot.

[cc @dshiga, @briandoconnor, @ttung , @mikebaumann]

**Comment by ttung** [comment]
You can think of files more like inodes.  The name of a file entry is stored in the bundle.

**Comment by xbrianh** [comment]
The DSS originally included a 1:1 constraint between files and bundles as an optimization. However, after some discussion, we have concluded that an N:N mapping should not include undue overhead. We will pursue this enhancement.

Note that the worthy topic of the meta-data content of analysis bundles is somewhat orthogonal to this issue. We may wish to move that conversation to a different ticket.

**Comment by hannes-ucsc** [comment]
I'm fine with not overloading this with copy forward discussion. Especially considering that I was wrong about where the file name resides, as @ttung points out.

Tell me if this is wrong:

Currently bundle to file is 1:N (https://en.wikipedia.org/wiki/One-to-many_(data_model). One bundle can have multiple files. One file can belong to only one bundle.

The relationship between file and blob is N:1. A file can only refer to one blob, one blob can be referred to by many files.

What extrinsic data is associated with a file object? I'm starting to suspect that they are redundant.

**Comment by ttung** [comment]
file obj is just a way to retain a tracking history of a file, I think, i.e., list all the versions of a file.  also it has creator_uid, but that's probably not even set now.
