### ISSUE TITLE
Notification on delete event

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/data-store#1179]
As a user of the eventing system I would like to get a notification when an object is deleted so that I can update my internal indexes.

**Comment by hannes-ucsc** [comment]
A subscription with this ES query will get notified on deleted bundles:

```
{
    "query": {
        "bool": {
            "must": [
                {
                    "term": {
                        "admin_deleted": True
                    }
                }
            ]
        }
    }
}
```

The problem is that this will match every deleted bundle, not just deleted bundles that match the subscribers original query. The subscriber would have to determine if the deleted bundle affects them or not. If that's acceptable, we can close this. 

If not, we need to notify *before* the deletion is made (with the original bundle document) not after (with the tombstone). I'm estimating this to be 3-5 person days for implementation plus how ever much it takes to get it through the PR review process.

**Comment by kozbo** [comment]
@caaespin see above
