### ISSUE TITLE
Checkout should not overwrite duplicate objects, rather refresh their TTLs

### ISSUE THREAD

**Issue by mweiden** [HumanCellAtlas/data-store#1367]
## User Story 1
* As a user of the DCP consumer API
* I want the DSS to refresh TTLs on duplicate objects in check out buckets rather than overwriting them
* so that time to export is reduced for "cached" objects.

## ~User Story 2~
* ~As an operator of the DSS~
* ~I want to refresh TTLs on duplicate objects in check out buckets rather than overwriting them~
* ~so that the cost of exporting objects is reduced.~

## Definition of Done
- [ ] Check out requests citing duplicate bundles, files, and bucket combinations does not result in a new copy operation
- [ ] The TTLs on the duplicate objects stored in the bucket are refreshed

**Comment by calvinnhieu** [comment]
TTLs can not be refreshed without overwriting an S3 object since its `Last-Modified` field is immutable (the same is true for GS):
https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html#object-metadata

The current checkout implementation "refreshes the TTL" of an object by overwriting it when it is requested near its expiration date. The current implementation also waits for the overwrite to complete before returning the file - this will be optimized to satisfy User Story 1. User Story 2 is not possible.

**Comment by ttung** [comment]
It is possible to design this such that we have a log-watching daemon that monitors access to the bucket, and only removes items that have not been accessed for a while.  The design complexity of that argues strongly for what we have now, but let's that possibility in mind in case costs make it a necessity.
