### ISSUE TITLE
Notification failed during smoketest

### ISSUE THREAD

**Issue by Bento007** [HumanCellAtlas/data-store#1386]
See https://github.com/HumanCellAtlas/data-store/issues/1357#issuecomment-401939228

https://travis-ci.com/HumanCellAtlas/data-store/builds/77884346

```
======================================================================
ERROR: test_smoketest (__main__.Smoketest) [aws]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_smoketest.py", line 224, in test_smoketest
    self.smoketest(**param)
  File "tests/test_smoketest.py", line 215, in smoketest
    obj = s3.get_object(Bucket=self.notification_bucket, Key=notification_key)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.
----------------------------------------------------------------------
```

## Definition of Done
Find a cause for the issue and create tickets needed to fix.

**Comment by Bento007** [comment]
@hannes-ucsc If you have any clues, I'd appreciate your help

**Comment by hannes-ucsc** [comment]
1) Extracted all relevant uuids (subscription and notification key) and plugged them into ELK:

`(699111fa-ff9b-4c99-8840-55a169ac89c0 OR e8e369d4-8f6b-494b-a8d9-f42f47354203 OR 15063188-23d5-47e9-befe-20d2a76b9e6e OR 86a8cc4c-077c-402f-9b4f-3dd7fd5c1398 OR 26729545-ebcf-4ed2-9810-ba620caf736e OR d6ee698b-50af-4934-8a4e-ec71d2f40b8c OR 1fa6ed93-2788-479b-88c4-6e3b11e4d53c OR d8e58092-0a39-4779-be90-8dc5b08b1f37) AND Successfully`

https://logs.dev.data.humancellatlas.org/_plugin/kibana/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-07-02T07:00:00.000Z',mode:absolute,to:'2018-07-02T19:00:00.000Z'))&_a=(columns:!('@log_group','@message'),filters:!(),index:'*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'(699111fa-ff9b-4c99-8840-55a169ac89c0+OR+e8e369d4-8f6b-494b-a8d9-f42f47354203+OR+15063188-23d5-47e9-befe-20d2a76b9e6e+OR+86a8cc4c-077c-402f-9b4f-3dd7fd5c1398+OR+26729545-ebcf-4ed2-9810-ba620caf736e+OR+d6ee698b-50af-4934-8a4e-ec71d2f40b8c+OR+1fa6ed93-2788-479b-88c4-6e3b11e4d53c+OR+d8e58092-0a39-4779-be90-8dc5b08b1f37)+AND+Successfully')),sort:!('@timestamp',desc))

This gives all successful notifications.

2) Parsed the UUIDs from those messages and put into a spreadsheet:

https://docs.google.com/spreadsheets/d/1_6kz2lSL8GlWQ13DlP-DB97vpeEcjgTfpvf76ai6SUM/edit?usp=sharing

Currently the indexer is invoked up to three times for the same BVR (bundle version replica). This must be a problem with the S3-SNS relay that Domovoi sets up. This needs more investigation. 

Detailed breakdown: The smoke test currently has two subtests and each subtest creates one bundle version. There are two replicas, so we should see four indexing events, one per BVR. In this test run there are ten, not four, events: three BVRs with three events each, and one BVR with one event. Each event led to one successful notification. Which is why I think the notifier is off the hook. The deletion of the notification objects in S3 (happens during tearDown after both subtests finish) did not fail, indicating that all notification objects existed at the end of the test.

**Comment by Bento007** [comment]
I'll investigate if duplicate topics exist for bundles.

**Comment by Bento007** [comment]
Additional tickets have been created to fix and continue investigation. See #1410
