### ISSUE TITLE
Store Audit logs in one place

### ISSUE THREAD

**Issue by Bento007** [HumanCellAtlas/data-store#1666]
## User story
* As a operator
* I want to store all audit logs in one place
* to reduce audit log management complexity

## Definition of done
AWS cloud trail logs are stored in the S3 audit log bucket
GCP stack driver logs are store in the s3 audit log bucket.

depends on #1665

**Comment by kozbo** [comment]
Verify that we can use stackdriver to get audit logs

**Comment by DailyDreaming** [comment]
Implemented here: https://github.com/HumanCellAtlas/logs/tree/master/apps/gcp_to_cwl

Logs are accessible via CloudWatch but not StackDriver.  StackDriver only propogates the logs down the line to CloudWatch.

**Comment by DailyDreaming** [comment]
Checking the implementation of this, I can mark this as done, though the Log Groups could use renaming since AWS and Google follow different conventions (see below).  Also, I'd guess a few hundred of those Log Groups could be deleted as cruft.

The audit logs are a bit different.  Though there's one audit Log Group for all AWS CloudTrail feeds (`/aws/cloudtrail/audit-and-data-access`).  There is a Log Group for each Google component on the other hand.  AWS also logs many more messages.  Some weird ones too, like it was showing I was making `GetBucketWebsite` calls, which I think it just a part of loading the bucket in the browser?  Each Google component has 1 to 2 log (short) entries while the AWS components have hundreds, but I verified that it updates when I update a Google bucket policy or lifecycle.

Some points, currently logs expire in 3 months.  Matt W. is changing this to 5 years soon, at David Bernick's suggestion.
