### ISSUE TITLE
make deploy-infra: CreateDomainName operation: Caller does not have permissions to create a Service Linked Role

### ISSUE THREAD

**Issue by brainstorm** [HumanCellAtlas/data-store#1726]
## Software version (git hash, date, branch)

81547e1
2018-11-14
master

## Expected behavior

I would have expected that the API gateway CreateDomainName process has enough permissions to carry on the AWS side, but that's not documented and policies (minimal permissions to be able to deploy) are not in place for deployment.

## Actual behavior

```
$ ./create_regional_domain_name.py --domain-name DOMAIN --certificate-arn arn:aws:acm:ap-southeast-2:ACCOUNT_ID:certificate/ARN_HASH --zone-id HOSTED_ZONE_ID
(...)
Traceback (most recent call last):
  File "./create_regional_domain_name.py", line 21, in <module>
    endpointConfiguration={'types': ["REGIONAL"]}
  File "/home/ubuntu/hca-venv/lib/python3.7/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ubuntu/hca-venv/lib/python3.7/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDeniedException) when calling the CreateDomainName operation: Caller does not have permissions to create a Service Linked Role.
```

## Steps to reproduce the behavior

`make deploy-infra`

**Comment by brainstorm** [comment]
Suitable policy and permissions for those actions are documented in:

https://github.com/amplify-education/serverless-domain-manager/issues/112#issuecomment-377032301

https://aws.amazon.com/blogs/security/introducing-an-easier-way-to-delegate-permissions-to-aws-services-service-linked-roles/

**Comment by melainalegaspi** [comment]
Creating a domain is now done manually, taken out of Terra form

**Comment by brainstorm** [comment]
Sad :/

**Comment by amarjandu** [comment]
the DSS moved away from using the regional_domain_names, there still should be additional work around creating regional replica's in the future (esp if we would like to host a replica in EU/Asia) 

The issue here looks like the account/role that was being used to call the ./create_regional_domain_name did not have  sufficient privileges to perform the operation, @brainstorm thanks for sharing the links, it looks like there could be improvement around documenting what permissions an operator should have on the account, i dont think this has been needed in the past from internal developers because of our access levels that we get through our assumed role.
