### ISSUE TITLE
Subscriptions are added but not listed

### ISSUE THREAD

**Issue by jessebrennan** [HumanCellAtlas/data-store#1957]
## Software version (git hash, date, branch)
This occurred on commit e767117db556903367ac41bc39f64a0720461fd3 which was the latest version of integration as of 6 March 2019.

## Expected behavior
Adding a subscription and then listing a subscription should list the subscription added.

## Actual behavior
Listing subscriptions not show your subscription if it was an Elasticsearch query.

## Steps to reproduce the behavior

* Add an Elastic search subscription
* `response = dss_client.get_subscriptions(replica='aws')`
  `response` is `[]`

**Comment by xbrianh** [comment]
Please try
```
response = dss_client.get_subscriptions(replica='aws', subscription_type='elasticsearch')
```

**Comment by hannes-ucsc** [comment]
Assuming the workaround works, this change in behavior broke backwards-compatibility. The default should be to list subscriptions of all types.

**Comment by hannes-ucsc** [comment]
The commit @jessebrennan linked wasn't the culprit, it was https://github.com/HumanCellAtlas/data-store/pull/1915 and https://github.com/HumanCellAtlas/data-store/pull/1822.

What makes this even more insidious is that the DSS client caches the swagger spec for seven days so the added parameter didn't show up in the method signatures, and passing it in had no effect.

Furthermore, it makes zero sense to require a subscription ID AND the `subscription_type` for DELETE. The subscription UUID is globally unique and should therefore be sufficient to retrieve a subscription. Returning a 404 for an existing subscription just because the `subscription_type` parameter wasn't supplied is surprising to say the least.

Please consider the downstream impact of backwards-compatibility breaking changes like this and communicate them to collaborators in a pro-active and timely fashion. No one from my team was notified. No one from my team was requested as a reviewer on any of the PRs for this. This took us completely by surprise and cost me day of work debugging.

**Comment by DailyDreaming** [comment]
Closing this.
