### ISSUE TITLE
Circular dependency in deployment documentation

### ISSUE THREAD

**Issue by natanlao** [HumanCellAtlas/data-store#1960]
The deployment documentation specifies that `./scripts/populate_lambda_ssm_parameters.py` must be run as a prerequisite to deploying the DSS. However, `scripts/populate_lambda_ssm_parameters.py:137` requires that `DSS_ES_ENDPOINT` be set. As the ElasticSearch domain is provisioned with Terraform during deployment, this condition cannot be met.

https://github.com/HumanCellAtlas/data-store/blob/99cdd1ddc9047d1688ebcb72455f570f2071307c/scripts/populate_lambda_ssm_parameters.py#L137

**Comment by amarjandu** [comment]
Documentation structure does not have a straightforward flow through a deployment, ideally terraform would be used to create the elasticsearch instance, and provide the `DSS_ES_ENDPOINT` so that the values could be exported before performing the `./scripts/populate_lambda_ssm_parameters.py` there would also need to be the SOURCE IP that are permitted to operate within the DSS to be established and added to the access policy of terraform. 

This may call for a rewrite of the `README.md`
