### ISSUE TITLE
Scale daemons/dss-index to handle bundles with ~10^6 files

### ISSUE THREAD

**Issue by xbrianh** [HumanCellAtlas/data-store#2024]

**Comment by DailyDreaming** [comment]
Okay, so we've run into some hard limits on this.

`dss-index-dev` broke trying to index the ~10^6 file bundles with a pipefail because they are longer than the 100mb limit that AWS-managed elasticsearch instances seem to impose: https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/aes-limits.html#network-limits

This seems to be configurable only if running a user-managed elasticsearch instance (e.g. hosted via EC2) by updating the `/etc/elasticsearch/elasticsearch.yml` file with something like `http.max_content_length="1000mb"` and restarting the instance.  Because our ES instances are AWS managed though, [I'm not sure that we can do this](https://stackoverflow.com/questions/55541625/aws-elasticsearch-cluster-method-to-update-http-max-content-length).

So the best solution seems to be waiting for the postgres jsonb query service being developed.  An easier stopgap solution in the meantime is limiting the indexing of manifests over a certain size.

On linux EXT4 (and most other linux distros), the max file name length is 255 char, and the max path length is 4096 char.  Metadata is usually about 380 bytes.

Since our file size limit is 100mb (104857600 bytes), this means a limit of:

`104857600/(4096+380) = roughly 23426 files per bundle`

So we should limit bundle sizes to around this in the meantime.

**Comment by xbrianh** [comment]
closed via #2031
