### ISSUE TITLE
SPIKE - discuss other ways to optimize checkout

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/data-store#2140]

**Comment by xbrianh** [comment]
Checkout optimization may be accomplished by
  - Placing objects into the checkout cache upon creation.
  - Reducing the need for downstream components to download metadata files by placing content into an index.
  - Improving checkout initiation logic in the dcp-cli

Otherwise I am not aware of further possibilities to enhance to checkout performance. However, we should proactively seek input from downstream components about the user experience provided by the DSS.
