### ISSUE TITLE
Collection size is limited by maximum request size

### ISSUE THREAD

**Issue by natanlao** [HumanCellAtlas/data-store#2279]
Related to HumanCellAtlas/data-store-scale-test#11:

> For the Pilot release, the collections system should be able to handle CRD operations with ~5 million bundles less than 30 seconds (gateway timeout).

When making a `PUT /collections` request with a collection that contains five million bundles, the request fails with a `SwaggerAPIException` (413 Request Entity Too Large). @DailyDreaming suggests that the `PUT /collections` endpoint can be extended to accept a file defining a collection to remove this constraint.

**Comment by xbrianh** [comment]
The collections API is meant to be inline (data is not passed in by reference) and synchronous (requests should finish within the 30 API Gateway timeout). To create a large collection, the [PATCH /collection](https://github.com/HumanCellAtlas/data-store/blob/b74823caca79646555330ab991c2e213f289edcf/dss-api.yml#L1226-L1388) endpoint should be used.

In this case, you have run up against the API Gateway request payload [limit of 10 MB](https://docs.aws.amazon.com/apigateway/latest/developerguide/limits.html), which the DSS API should prevent by limiting the number of items in a PUT /collection request. This is the real issue here.

**Comment by natanlao** [comment]
Okay, thanks for the clarification!
