### ISSUE TITLE
Limit the number of subscriptions per user

### ISSUE THREAD

**Issue by xbrianh** [HumanCellAtlas/data-store#2308]
Users should not be able to have an unlimited number of subscriptions in the DSS.

For now a reasonable limit may be 5.

**Comment by kislyuk** [comment]
Let's start with a much higher limit. IMHO we should discuss how to make subscriptions more scalable instead of trying to impose limits that are likely to result in API usability issues down the line.

- Can we automatically, quickly disable subscriptions that have notification delivery failures?
- Can we batch deliveries so there is less overhead?
- Can we refuse to create exact duplicate subscriptions?

An analysis service using a single identity to manage subscriptions for multiple pipelines in multiple test/production environments will immediately hit this limit and be blocked.

**Comment by DailyDreaming** [comment]
@kislyuk How high were you thinking?  For context, `dev` is breaking right now due to a large number of subscriptions recently added (in the thousands) that's causing problems.

**Comment by xbrianh** [comment]
@kislyuk I completely agree with all of that. My concern in the near term is preventing developers from setting off fork bombs during scale testing, which is unfortunately easy due to the built-in retry architecture of the notification systems. In the far term, disabling unserviceable endpoints, along with your other suggestions, are the right path.

Perhaps we can cap it at 100 subscriptions per user for now. That's a lot of headroom compared to current usage. This can be increased as our notification scalability improves.

**Comment by kislyuk** [comment]
100 sounds good to me, along with a documented process for raising the limit.

**Comment by DailyDreaming** [comment]
Addressed by #2309 and #2310.
