### ISSUE TITLE
`dss-ops.py secrets` error handling is overly broad

### ISSUE THREAD

**Issue by natanlao** [HumanCellAtlas/data-store#2423]
https://github.com/HumanCellAtlas/data-store/blob/fbb073543290082aab4f2950c5a71858bde4ba4f/dss/operations/secrets.py#L123

`python scripts/dss-ops.py secrets get` will indicate that a secret is not found if any `ClientError` is raised, even if a different error (e.g., a secret not being retrievable because it has been marked for deletion) is at fault.

**Comment by chmreid** [comment]
Thanks for pointing this out. This is something that was addressed in PR #2324 (which was closed), but part of the reason that PR was closed was because it was affecting the implementation of secrets as well as adding parameter store functionality. A fix has been written (see https://github.com/HumanCellAtlas/data-store/pull/2324/files#diff-34535c41128c607579072d3e63dd4143R25-R49 the `secret_is_gettable()` and `secret_is_settable()` methods). I will contribute the fix via a new PR soon.

**Comment by natanlao** [comment]
Great, thanks! I'll reassign this to you, then.

**Comment by chmreid** [comment]
Closed by #2451
