### ISSUE TITLE
Data checkout feature

### ISSUE THREAD

**Issue by Bento007** [HumanCellAtlas/data-store#536]
## Why
Story Statements:

As an end user I would like to be able to make a copy of the data to my account in a cloud provider so that I can directly access the data.

As an end user I would like to access the data on high performance servers in the HCA cloud environment so that I can directly access the data for HPC uses.

spec: https://docs.google.com/document/d/1rBUfWRUo_UEZKXFJ9gfP980sN1qzPiiOpanWDHdtTv8/edit

The data checkout service attempts to solve two problems:

1. Some tools impose specific requirements on the names of the objects. Some other tools expect two related files to have the same prefix. Since we store our files as content-addressed blobs, we cannot provide the naming semantics these tools require. The checkout service can execute this rename.
2. This neatly solves the problem of cold storage (at least on AWS, where cold storage can have long latencies).

**Comment by Bento007** [comment]
Please create a story statement to capture the purpose of this issue. Ex: As a < type of user >, I want < some goal > so that < some reason >.

**Comment by ttung** [comment]
The data checkout service attempts to solve two problems:

1. Some tools impose specific requirements on the names of the objects.  Some other tools expect two related files to have the same prefix.  Since we store our files as content-addressed blobs, we cannot provide the naming semantics these tools require.  The checkout service can execute this rename.
2. This neatly solves the problem of cold storage (at least on AWS, where cold storage can have long latencies).

**Comment by Bento007** [comment]
break into:
prototype aws, prototype google, deployment infrastructure, tests, fault tolerance and assign to @amork

**Comment by kozbo** [comment]
I assume that this task will take several sprints (hence the epic label). If so then we should have separate issues to track the progress. These issues should be listed here and the issue labeled as an epic should remain in the Data-store backlog column.

**Comment by kozbo** [comment]
### TASKS
- [ ] #620 data checkout prototype google

**Comment by kozbo** [comment]
closing epic, all items done
