### ISSUE TITLE
Create index lazily when indexing documents

### ISSUE THREAD

**Issue by Bento007** [HumanCellAtlas/data-store#690]
### On which version of the code did the bug occur? (git hash, date, branch, be specific)
master 2e38241
### Actual behavior
Check if index exists, if index exists add the documents to the index.
### Expected behavior
try to index the documents, if indexing fails because index does not exist create the index and index the document. 

This will reduce the number of round trips to the ES server.

**Comment by Bento007** [comment]
@hannes-ucsc @mikebaumann What do you think of this change?

**Comment by hannes-ucsc** [comment]
With the addition of optimistic locking, things have change a little bit. Currently, the sequence when indexing a bundle with a given FQID is:

1) create index
2) read existing version numbers for the FQID from all indices (normally at most one)
3) read existing document from the index it belongs in
4) compare new and existing document
5) if different write new document to index it belongs in
6) delete all documents for that FQID in other indices (usually none)

This optimization would still apply. We could move step 1) to occur only if step 5) fails. But the error response from ES must be unambiguously indicating that indexing failed because the index doesn't exist.

However, considering the many (I count five in my head) other ES round-trips that occur when we index a document, the performance gain isn't gonna be huge. I would treat this as a low priority.

**Comment by Bento007** [comment]
removing ES, bug no longer relevant
