### ISSUE TITLE
Prevent concurrent deployments and integration tests in one stage

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/data-store#692]
Besides being a sensible thing to do, this would enable us to run integration tests as part of PR builds.

**Comment by xbrianh** [comment]
Since integration tests typically depend upon deployed lambdas, integration testing should be performed post-deploy. Running integration tests prior to deployment may be misleading.

The Build Box `dev` pipeline is currently configured as `unit test` -> `deploy` -> `integration_test` -> `promote to int maybe`. Except for merges in rapid succession, this should mostly prevent concurrent builds.
