### ISSUE TITLE
Separate integration and standalone tests & decorate test mode at class level

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/data-store#820]
#815 decorates all remaining tests with either `@testmode.standalone` or `@testmode.integration`. For some `TestCase` subclasses all test methods are decorated `@testmode.standalone`. @ttung proposes that these decorations should be removed and a decoration should be placed on the containing testcase subclass. @Bento007 proposes that, if a class with predominantly standalone tests contains a lone integration test, those tests should be moved out into a separate class. The `testmode` decorations can then also be moved to the class level.

**Comment by ttung** [comment]
Actually, I prefer we put them on each test method because if you do it on a class-level, then add a single test of the opposite type, then you have a lot of spurious changes.

I just mentioned it because some PRs with the class-level switch already went through, and I feel we should be clear what approach this team should take.

**Comment by hannes-ucsc** [comment]
The policy could be that we shouldn't mix IT and stand-alone tests in the same class. This would prevent the spurious changes problem. Wouldn't an IT typically require specific setup anyhow, and therefore feel out of place in a class with mostly standalone tests? OTOH, I could imagine a class with mostly IT have a few standalone tests for sanity checks that require no setup/teardown.
