### ISSUE TITLE
DSS put file for large files (async copy) on AWS may incorrectly fail etag comparison due to differing part size/count

### ISSUE THREAD

**Issue by mikebaumann** [HumanCellAtlas/data-store#958]
### Expected behavior
DSS put file should work for large (async copy) files on AWS regardless of the part size/count used to create the cloud source file.
### Actual behavior
When a large AWS source file was copied into the source bucket using a multipart size/count different than the DSS uses for the async copy, the put file operation incorrectly fails its final etag comparison, because the part size/count is factored into the etag computation.
This may be seen in CloudWatch logs for `dss-s3-copy-write-metadata-sfn` as follows:
```
: AssertionError
Traceback (most recent call last):
File "/var/task/domovoi/app.py", line 127, in __call__
result = handler(event, context)
File "/var/task/domovoilib/dss/stepfunctions/s3copyclient/implementation.py", line 196, in join
assert composite_etag == state[_Key.SOURCE_ETAG]
AssertionError
```
If the assertion above is commented out, the DSS redployed, and the put file operation performed again, the differing etag values are as follows:
```
https://s3-us-west-2.amazonaws.com/cgp-commons-public/topmed_open_access/014a9de5-cb88-5e37-a196-b6e3ab30fff6/NWD759405.recab.cram
Etag
1710ce7f6fc2a65e3bbe9292b772ad44-2512
Size
21070337861

https://s3-us-west-2.amazonaws.com/commons-dss-commons/blobs/594dc85f8a00d15b6e391a05c218ee3e4a8d8afc6a068fe8d198789ad2754927.1ebcba06ab845cbb429458ca32deb455f911a7d7.c0a1c3aa09428d075727422e7167f86d-314.275d7174
Etag
c0a1c3aa09428d075727422e7167f86d-314
Size
21070337861
```

The original source file and async copied file in the DSS bucket were both downloaded and verified to be identical using a full binary byte comparison.

This was observed with data-store master commit 30c7cf1371a9edf2de16f93a3f1b22ed640b8b31

**Comment by ttung** [comment]
This is expected and correct behavior.

**Comment by hannes-ucsc** [comment]
I briefly glanced at the code when Michael showed asked me about this. I didn't see that the destination part size was derived from the source part size, so the fact that they are the same in most scenarios seems incidental, rendering the assertion unwarranted.  We either need to remove the assertion or derive the destination part size from the source part size.

I would prefer the former because tying the source part size to the destination part size will prove to be limiting with the *foreign blob* use cases that we're exploring at the moment.

**Comment by ttung** [comment]
This is by design.  Ingest is responsible for formatting the data the way the DSS expects.

If the issue is foreign blobs, then it's also a non-issue because you won't be copying the data.

**Comment by hannes-ucsc** [comment]
> This is by design

Could you point me at the spec that mentions this?

> Ingest is responsible for formatting the data the way the DSS expects.

Even *if* it spec'ed that way, I wouldn't want to rely on a MP part size to be used by another component in the system. It seems brittle and limiting, for very little benefit. The spec should be changed.

> If the issue is foreign blobs, then it's also a non-issue because you won't be copying the data.

I shouldn't have used the term foreign blob. Michael is exploring an alternative to foreign blobs which lets him import data from a bucket, avoiding the initial copy into the staging bucket. There are only minimal changes blocking him from that. This is one of them.

Before we shoot this down, let's escalate it to the stakeholders. And, BTW, I am happy to take this on as the assignee.

**Comment by ttung** [comment]
https://docs.google.com/document/d/1KQeJOsLA_K32Z3rys0jF-A8NWcLyCoK_ruk6pEC1a7k/edit#

I propose we change it to the following:
1. In PUT /files, we record the promised checksum in the request.
2. Before the s3 copy completes, we assert that the calculated etag matches the promised checksum.

This preserves the data integrity promises and allows you to do what you need.

Note that you will still need to calculate all the other checksums.

**Comment by hannes-ucsc** [comment]
I don't see any mention in that document that all MP uploads and copies have to use the same part size. Correct me if I am wrong but I don't think we can claim that this behavior (requiring that source and destination part size matches) is by design.

As far as your proposal is concerned, I don't see how it changes anything. But I probably misunderstand it. Whether I get the source ETag from a object itself or via the REST API side channel, I still have to match the source part size for the MP copy in order to end up with the same destination ETag. BTW, deriving the part size from the ETag is impossible so I would need to get the part size via the side channel, not the ETag.

Another thing to keep in mind is that Amazon does not document the ETag algorithm for MP uploads or copies (as far as I know). They could decide any moment to change it, or phase a new one in, resulting in a mix of MP ETags in S3. I've battled with this issue in another project and decided to not rely on MP ETags for verification. For bucket-to-bucket copies, Amazon guarantees the integrity of the data. For uploads you need to verify each part's ETag, but not the composite object ETag. Amazon guarantees that it concatenates the parts correctly.

**Comment by ttung** [comment]
Note that the ingest mechanism is responsible for the calculations of the checksums.

You don't need to match the source part size on the data, but you need to calculate the checksums as if you had the same part sizes.  This is a fundamental requirement of the blue box, that it ensures data integrity.  The current design allows us to examine the file metadata and ensure that there is not some first-order corruption of the data.  If the checksum in the filename matches the cloud provider's checksum, we are probably good.

If your argument is that we should just accept an etag based on an arbitrary part size, then we need a mechanism to synchronize that data _consistently_.

(1) Yes, i'm aware Amazon does not document the etag algorithm, but there's so much code out there that depends on this.  It'd be extremely difficult for them to change it.

**Comment by hannes-ucsc** [comment]
I'm still trying to figure out where the disconnect is here. You may be under the impression that there is a fixed derivation from object size to part size, as suggested by the SO post our Swagger docs point at:

https://stackoverflow.com/questions/12186993/what-is-the-algorithm-to-compute-the-amazon-s3-etag-for-a-file-larger-than-5gb

There isn't. I can MP upload a 5MB file using an MP upload of a single part of 5MB. I can upload a 5GB file in a non-MP upload. I can upload a 5GB + 1 byte file in two parts. The first part 5GB, the second part one byte. This is officially documented here: https://docs.aws.amazon.com/AmazonS3/latest/dev/qfacts.html

**Comment by ttung** [comment]
I'm aware of all that.  We use (or we used to) that to test multipart uploads because we don't want the tests to take so long, so we used the smallest chunk possible.

I'll try to rephrase my proposal, and if it's still not clear, maybe you can field your proposal:

1. In PUT /files, we record the promised composite etag in the request.  The etag of the source file is not checked.
2. Before we merge the multipart upload, we assert that the calculated etag matches the promised checksum.

Therefore, the size of the parts of the source file is not consequential.  However, we still have to calculated the checksums according to the prescribed chunk sizes.

**Comment by hannes-ucsc** [comment]
I get it now. The thing I've been missing is that DSS assumes that all boxes agree on a specific way of computing an ETag:

https://github.com/HumanCellAtlas/checksumming_io/blob/master/checksumming_io/s3_etag.py#L10

Files less than 64MB get a basic ETag, files greater than that get a composite ETag, using a part size of 64MB. 

We should make that very clear in the `PUT /files` doc. And we should call that type of checksum the *DSS ETag* from now on. 

So: This is not a bug, but a feature request. I agree that your proposal would work for @mikebaumann's use case. I would also like to propose that we take it one step further:

We eliminate the requirement that the staged object be tagged with the four checksums (SHA1, SHA256, DSS ETag and CRC32) and instead require that they be submitted as part of `PUT /files`. This is more flexible as it allows using `PUT /files` with read-only buckets. I don't think this change will face opposition from the ingest team. I think this is what https://github.com/HumanCellAtlas/data-store/issues/911 is about.

**Comment by mikebaumann** [comment]
Thanks to you both for your work on this.
I would be very happy with the revised proposal as described by @hannes-ucsc above.
And, yes, this change is foundational for resolving #911.

**Comment by hannes-ucsc** [comment]
I think it's better to continue this effort in another ticket: #965.
